// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9E5Qz14c7uOHjpzDmyy-SP1dZ4IY9kPU',
    appId: '1:102674916052:web:ef9bb3b6319bf6f6a59141',
    messagingSenderId: '102674916052',
    projectId: 'tes-firebase-27c65',
    authDomain: 'tes-firebase-27c65.firebaseapp.com',
    databaseURL: 'https://tes-firebase-27c65.firebaseio.com',
    storageBucket: 'tes-firebase-27c65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWqOttXrUa89svAQNrhDG3yxM3GKF3-nI',
    appId: '1:102674916052:android:7133e2a1fa82e7bda59141',
    messagingSenderId: '102674916052',
    projectId: 'tes-firebase-27c65',
    databaseURL: 'https://tes-firebase-27c65.firebaseio.com',
    storageBucket: 'tes-firebase-27c65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLBsqph74KKq44ocp4iHOvEz8GDrUYuEY',
    appId: '1:102674916052:ios:008303f14bf04252a59141',
    messagingSenderId: '102674916052',
    projectId: 'tes-firebase-27c65',
    databaseURL: 'https://tes-firebase-27c65.firebaseio.com',
    storageBucket: 'tes-firebase-27c65.appspot.com',
    iosClientId: '102674916052-nf06nmtf7fn2u3qfq9n80e3nfnuu388u.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanggo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLBsqph74KKq44ocp4iHOvEz8GDrUYuEY',
    appId: '1:102674916052:ios:008303f14bf04252a59141',
    messagingSenderId: '102674916052',
    projectId: 'tes-firebase-27c65',
    databaseURL: 'https://tes-firebase-27c65.firebaseio.com',
    storageBucket: 'tes-firebase-27c65.appspot.com',
    iosClientId: '102674916052-nf06nmtf7fn2u3qfq9n80e3nfnuu388u.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanggo',
  );
}
